[package]
name = "zk-prover-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy = "1.0.5"
alloy-eips = "1.0.5"
dotenv = "0.15.0"
tokio = { version = "1", features = ["full"] }
async-trait = "0.1"